#Makefile source, object and dependency 
#Modify this file after source change.

#code 
CORE_DEPS_LOCAL = ax_debug.h utest.h ax_buffer.h ax_string.h ax_timer.h \
				  fd_poller.h kqueue.h \
				  ax_hashmap.h mem_pool.h

CORE_OBJS_LOCAL = ax_debug.o utest.o ax_buffer.o ax_string.o ax_timer.o \
				  fd_poller.o kqueue.o \
				  mem_pool.o 

#add path prefix
CORE_OBJS = $(addprefix core/, $(CORE_OBJS_LOCAL))
CORE_DEPS = $(addprefix src/core/, $(CORE_DEPS_LOCAL))


NETD_DEPS_LOCAL = 
NETD_OBJS_LOCAL = netd.o

NETD_OBJS = $(addprefix netd/, $(NETD_OBJS_LOCAL))
NETD_DEPS = $(addprefix src/netd/, $(NETD_DEPS_LOCAL))
