#Makefile source, object and dependency 
#Modify this file after source change.

#code 
CORE_DEPS_LOCAL = stdheader.h ax_debug.h utest.h ax_buffer.h ax_string.h ax_timer.h \
				  fd_poller.h kqueue.h \
				  ax_hashmap.h mem_pool.h connect.h  os_misc.h

CORE_OBJS_LOCAL = ax_debug.o utest.o ax_buffer.o ax_string.o ax_timer.o \
				  fd_poller.o kqueue.o \
				  mem_pool.o connect.o os_misc.o

#add path prefix
CORE_OBJS = $(addprefix core/, $(CORE_OBJS_LOCAL))
CORE_DEPS = $(addprefix src/core/, $(CORE_DEPS_LOCAL))


CGATE_DEPS_LOCAL = node_init.h client_mgr.h connect_worker.h
CGATE_OBJS_LOCAL = main.o node_init.o connect_worker.o client_mgr.o

CGATE_OBJS = $(addprefix cgate/, $(CGATE_OBJS_LOCAL))
CGATE_DEPS = $(addprefix src/cgate/, $(CGATE_DEPS_LOCAL))
